"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.  # noqa: E501

    The version of the OpenAPI document: 1.0.11-2025102807
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from intersight.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    set_model_init_error,
    OpenApiModel
)
from intersight.exceptions import ApiAttributeError


def lazy_import():
    from intersight.model.asset_device_registration_relationship import AssetDeviceRegistrationRelationship
    from intersight.model.compute_alarm_summary import ComputeAlarmSummary
    from intersight.model.compute_blade_relationship import ComputeBladeRelationship
    from intersight.model.equipment_chassis_relationship import EquipmentChassisRelationship
    from intersight.model.equipment_interconnect_relationship import EquipmentInterconnectRelationship
    from intersight.model.equipment_locator_led_relationship import EquipmentLocatorLedRelationship
    from intersight.model.equipment_shared_graphics_card_relationship import EquipmentSharedGraphicsCardRelationship
    from intersight.model.graphics_card_relationship import GraphicsCardRelationship
    from intersight.model.inventory_device_info_relationship import InventoryDeviceInfoRelationship
    globals()['AssetDeviceRegistrationRelationship'] = AssetDeviceRegistrationRelationship
    globals()['ComputeAlarmSummary'] = ComputeAlarmSummary
    globals()['ComputeBladeRelationship'] = ComputeBladeRelationship
    globals()['EquipmentChassisRelationship'] = EquipmentChassisRelationship
    globals()['EquipmentInterconnectRelationship'] = EquipmentInterconnectRelationship
    globals()['EquipmentLocatorLedRelationship'] = EquipmentLocatorLedRelationship
    globals()['EquipmentSharedGraphicsCardRelationship'] = EquipmentSharedGraphicsCardRelationship
    globals()['GraphicsCardRelationship'] = GraphicsCardRelationship
    globals()['InventoryDeviceInfoRelationship'] = InventoryDeviceInfoRelationship


class PciNodeAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('class_id',): {
            'PCI.NODE': "pci.Node",
        },
        ('object_type',): {
            'PCI.NODE': "pci.Node",
        },
        ('lifecycle',): {
            'NONE': "None",
            'ACTIVE': "Active",
            'DECOMMISSIONED': "Decommissioned",
            'DISCOVERYINPROGRESS': "DiscoveryInProgress",
            'DISCOVERYFAILED': "DiscoveryFailed",
            'FIRMWAREUPGRADEINPROGRESS': "FirmwareUpgradeInProgress",
            'SECUREERASEINPROGRESS': "SecureEraseInProgress",
            'SCRUBINPROGRESS': "ScrubInProgress",
            'BLADEMIGRATIONINPROGRESS': "BladeMigrationInProgress",
            'SLOTMISMATCH': "SlotMismatch",
            'REMOVED': "Removed",
            'MOVED': "Moved",
            'REPLACED': "Replaced",
            'MOVEDANDREPLACED': "MovedAndReplaced",
        },
        ('oper_reason',): {
            'None': None,
            'UNKNOWN': "Unknown",
            'OK': "OK",
            'OFFLINE': "Offline",
            'MISSING': "Missing",
            'HEALTHWARNING': "HealthWarning",
            'HEALTHCRITICAL': "HealthCritical",
            'TEMPERATUREWARNING': "TemperatureWarning",
            'TEMPERATURECRITICAL': "TemperatureCritical",
            'INPUTVOLTAGEWARNING': "InputVoltageWarning",
            'INPUTVOLTAGECRITICAL': "InputVoltageCritical",
            'OUTPUTVOLTAGEWARNING': "OutputVoltageWarning",
            'OUTPUTVOLTAGECRITICAL': "OutputVoltageCritical",
            'OUTPUTCURRENTWARNING': "OutputCurrentWarning",
            'OUTPUTCURRENTCRITICAL': "OutputCurrentCritical",
            'SPEEDWARNING': "SpeedWarning",
            'SPEEDCRITICAL': "SpeedCritical",
            'FANMISSINGWARNING': "FanMissingWarning",
            'FANSMISSINGCRITICAL': "FansMissingCritical",
            'IOCARDPOSTWARNING': "IocardPostWarning",
            'ASICPOSTWARNING': "AsicPostWarning",
            'TPMCRITICAL': "TPMCritical",
            'FRUSTATECRITICAL': "FruStateCritical",
            'FRUSTATEWARNING': "FruStateWarning",
            'ALTERNATEIMAGEWARNING': "AlternateImageWarning",
            'SELECTEDIMAGEWARNING': "SelectedImageWarning",
            'SWITCHHEALTHCRITICAL': "SwitchHealthCritical",
            'LOWMEMORYCRITICAL': "LowMemoryCritical",
            'LOWMEMORYWARNING': "LowMemoryWarning",
            'POWERCRITICAL': "PowerCritical",
            'POWERWARNING': "PowerWarning",
            'THERMALSAFEMODECRITICAL': "ThermalSafeModeCritical",
            'PSUREDUNDANCYLOSTCRITICAL': "PsuRedundancyLostCritical",
            'INPUTPOWERWARNING': "InputPowerWarning",
            'INPUTPOWERCRITICAL': "InputPowerCritical",
            'OUTPUTPOWERWARNING': "OutputPowerWarning",
            'OUTPUTPOWERCRITICAL': "OutputPowerCritical",
            'FANGENERALCRITICAL': "FanGeneralCritical",
            'POWERSUPPLYGENERALCRITICAL': "PowerSupplyGeneralCritical",
            'POWERSUPPLYINPUTWARNING': "PowerSupplyInputWarning",
            'POWERSUPPLYOUTPUTCRITICAL': "PowerSupplyOutputCritical",
            'POWERSUPPLYINPUTLOSTWARNING': "PowerSupplyInputLostWarning",
            'POWERSUPPLYUNRESPONSIVECRITICAL': "PowerSupplyUnresponsiveCritical",
            'POWERSUPPLYPREDICTIVEFAILURE': "PowerSupplyPredictiveFailure",
            'POWERSUPPLYDETECTIONFAILURE': "PowerSupplyDetectionFailure",
            'PSUFASTOVERCURRENTWARNING': "PsuFastOverCurrentWarning",
            'FANUNRESPONSIVECRITICAL': "FanUnresponsiveCritical",
            'MEMORYUNCORRECTABLEERROR': "MemoryUncorrectableError",
            'MEMORYTEMPERATUREWARNING': "MemoryTemperatureWarning",
            'MEMORYTEMPERATURECRITICAL': "MemoryTemperatureCritical",
            'MEMORYBANKERROR': "MemoryBankError",
            'MEMORYRANKERROR': "MemoryRankError",
            'MEMORYPOPERROR': "MemoryPopError",
            'MEMORYRASERROR': "MemoryRasError",
            'MEMORYMISMATCHERROR': "MemoryMismatchError",
            'MEMORYSPDERROR': "MemorySpdError",
            'MEMORYBISTERROR': "MemoryBistError",
            'MEMORYTYPEERROR': "MemoryTypeError",
            'MOTHERBOARDPOWERCRITICAL': "MotherBoardPowerCritical",
            'MOTHERBOARDTEMPERATUREWARNING': "MotherBoardTemperatureWarning",
            'MOTHERBOARDTEMPERATURECRITICAL': "MotherBoardTemperatureCritical",
            'MOTHERBOARDVOLTAGEWARNING': "MotherBoardVoltageWarning",
            'MOTHERBOARDVOLTAGECRITICAL': "MotherBoardVoltageCritical",
            'MOTHERBOARDPCHFUSEFAIL': "MotherBoardPCHFuseFail",
            'MOTHERBOARDCPLDIMAGEVERIFICATIONFAIL': "MotherBoardCPLDImageVerificationFail",
            'LOWLEVELCOMPONENTFAILURE': "LowLevelComponentFailure",
            'PROCESSORCATERR': "ProcessorCatErr",
            'PROCESSORTHERMTRIP': "ProcessorThermTrip",
            'COMPONENTNOTOPERATIONAL': "ComponentNotOperational",
            'OPERATIONALTHROUGHFAILOVER': "OperationalThroughFailover",
            'COMPONENTNOTREACHABLE': "ComponentNotReachable",
            'PROCESSORTEMPERATUREWARNING': "ProcessorTemperatureWarning",
            'PROCESSORTEMPERATURECRITICAL': "ProcessorTemperatureCritical",
            'PROCESSORPOWERCRITICAL': "ProcessorPowerCritical",
            'PROCESSORINTERNALERROR': "ProcessorInternalError",
            'PROCESSORBISTFAILURE': "ProcessorBISTFailure",
            'PROCESSORHANGINPOSTFAILURE': "ProcessorHangInPOSTFailure",
            'PROCESSORINITFAILURE': "ProcessorInitFailure",
            'PROCESSORCONFIGURATIONFAILURE': "ProcessorConfigurationFailure",
            'PROCESSORSMBIOSUNCORRECTABLECPUCOMPLEXERROR': "ProcessorSMBIOSUncorrectableCPUComplexError",
            'PCIENODERISERMISMATCH': "PCIeNodeRiserMismatch",
            'PCIENODERISER1MISSING': "PCIeNodeRiser1Missing",
            'PCIENODERISER2PRESENTCPU2ABSENT': "PCIeNodeRiser2PresentCPU2Absent",
            'PCIENODEPCIELINKCONFIGISSUE': "PCIeNodePCIeLinkConfigIssue",
            'PCIENODERISER1POWERFAULT': "PCIeNodeRiser1PowerFault",
            'PCIENODERISER2POWERFAULT': "PCIeNodeRiser2PowerFault",
            'PCIENODEPOWERFAULT': "PCIeNodePowerFault",
            'PCIENODEUNSUPPORTEDPCIECARDPRESENTONRISER1': "PCIeNodeUnsupportedPCIeCardPresentOnRiser1",
            'PCIENODEUNSUPPORTEDPCIECARDPRESENTONRISER2': "PCIeNodeUnsupportedPCIeCardPresentOnRiser2",
            'PCIENODEUNKNOWNPCIECARDPRESENTONRISER1': "PCIeNodeUnknownPCIeCardPresentOnRiser1",
            'PCIENODEUNKNOWNPCIECARDPRESENTONRISER2': "PCIeNodeUnknownPCIeCardPresentOnRiser2",
            'PCIENODEPRESENTXFM1ABSENT': "PCIeNodePresentXFM1Absent",
            'INVALIDCONNECTIONS': "InvalidConnections",
            'FEXREPLACED': "FexReplaced",
            'THERMALSAFEMODECRITICALSERVERSLOT1': "ThermalSafeModeCriticalServerSlot1",
            'THERMALSAFEMODECRITICALSERVERSLOT2': "ThermalSafeModeCriticalServerSlot2",
            'THERMALSAFEMODECRITICALSERVERSLOT3': "ThermalSafeModeCriticalServerSlot3",
            'THERMALSAFEMODECRITICALSERVERSLOT4': "ThermalSafeModeCriticalServerSlot4",
            'THERMALSAFEMODECRITICALSERVERSLOT5': "ThermalSafeModeCriticalServerSlot5",
            'THERMALSAFEMODECRITICALSERVERSLOT6': "ThermalSafeModeCriticalServerSlot6",
            'THERMALSAFEMODECRITICALSERVERSLOT7': "ThermalSafeModeCriticalServerSlot7",
            'THERMALSAFEMODECRITICALSERVERSLOT8': "ThermalSafeModeCriticalServerSlot8",
            'THERMALSAFEMODECRITICALXFM1': "ThermalSafeModeCriticalXFM1",
            'THERMALSAFEMODECRITICALXFM2': "ThermalSafeModeCriticalXFM2",
            'THERMALSAFEMODECRITICALIFM1': "ThermalSafeModeCriticalIFM1",
            'THERMALSAFEMODECRITICALIFM2': "ThermalSafeModeCriticalIFM2",
            'CHASSISAVAILABLEPOWERINSUFFICIENT': "ChassisAvailablePowerInsufficient",
            'CHASSISPOWERBUDGETINSUFFICIENT': "ChassisPowerBudgetInsufficient",
            'CHASSISPOWERINSUFFICIENT': "ChassisPowerInsufficient",
            'POWERBACKUPFAILEDCRITICAL': "PowerBackupFailedCritical",
            'POWERBACKUPFAILEDWARNING': "PowerBackupFailedWarning",
            'SPARECAPACITYWORNOUTCRITICAL': "SpareCapacityWornOutCritical",
            'SPARECAPACITYWORNOUTWARNING': "SpareCapacityWornOutWarning",
            'MEDIAINREADONLYCRITICAL': "MediaInReadOnlyCritical",
            'MEDIAINREADONLYWARNING': "MediaInReadOnlyWarning",
            'OVERALLSUBSYSTEMDEGRADEDCRITICAL': "OverallSubsystemDegradedCritical",
            'OVERALLSUBSYSTEMDEGRADEDWARNING': "OverallSubsystemDegradedWarning",
            'XFMUNSUPPORTEDCARDINPCIESLOT1': "XFMUnsupportedCardInPCIeSlot1",
            'XFMUNSUPPORTEDCARDINPCIESLOT2': "XFMUnsupportedCardInPCIeSlot2",
            'XFMUNKNOWNCARDINPCIESLOT1': "XFMUnknownCardInPCIeSlot1",
            'XFMUNKNOWNCARDINPCIESLOT2': "XFMUnknownCardInPCIeSlot2",
            'XFMPCIESWITCH1POWERFAULT': "XFMPCIeSwitch1PowerFault",
            'XFMPCIESWITCH2POWERFAULT': "XFMPCIeSwitch2PowerFault",
            'XFMPCIESWITCH1COMMUNICATIONFAILURE': "XFMPCIeSwitch1CommunicationFailure",
            'XFMPCIESWITCH2COMMUNICATIONFAILURE': "XFMPCIeSwitch2CommunicationFailure",
            'XFMCOMPUTESLOT1COMMUNICATIONFAILURE': "XFMComputeSlot1CommunicationFailure",
            'XFMCOMPUTESLOT2COMMUNICATIONFAILURE': "XFMComputeSlot2CommunicationFailure",
            'XFMCOMPUTESLOT3COMMUNICATIONFAILURE': "XFMComputeSlot3CommunicationFailure",
            'XFMCOMPUTESLOT4COMMUNICATIONFAILURE': "XFMComputeSlot4CommunicationFailure",
            'XFMCOMPUTESLOT5COMMUNICATIONFAILURE': "XFMComputeSlot5CommunicationFailure",
            'XFMCOMPUTESLOT6COMMUNICATIONFAILURE': "XFMComputeSlot6CommunicationFailure",
            'XFMCOMPUTESLOT7COMMUNICATIONFAILURE': "XFMComputeSlot7CommunicationFailure",
            'XFMCOMPUTESLOT8COMMUNICATIONFAILURE': "XFMComputeSlot8CommunicationFailure",
            'PCIENODEHOTSWAPCONTROLLER1FAULT': "PCIeNodeHotswapController1Fault",
            'PCIENODEHOTSWAPCONTROLLER2FAULT': "PCIeNodeHotswapController2Fault",
            'PCIENODEDCBRICK1FAULT': "PCIeNodeDcBrick1Fault",
            'PCIENODEDCBRICK2FAULT': "PCIeNodeDcBrick2Fault",
            'PCIENODEXFM1INCOMPATIBLE': "PCIeNodeXFM1Incompatible",
            'PCIENODEXFM2INCOMPATIBLE': "PCIeNodeXFM2Incompatible",
            'PCIENODEININVALIDSLOT': "PCIeNodeInInvalidSlot",
            'PCIESLOTPOWER': "PCIeSlotPower",
            'PCIESLOTAUXCABLEMISSING': "PCIeSlotAuxCableMissing",
            'UNSUPPORTEDCARDINPCIESLOT1': "UnsupportedCardInPCIeSlot1",
            'UNSUPPORTEDCARDINPCIESLOT2': "UnsupportedCardInPCIeSlot2",
            'UNSUPPORTEDCARDINPCIESLOT3': "UnsupportedCardInPCIeSlot3",
            'UNSUPPORTEDCARDINPCIESLOT4': "UnsupportedCardInPCIeSlot4",
            'UNKNOWNCARDINPCIESLOT1': "UnknownCardInPCIeSlot1",
            'UNKNOWNCARDINPCIESLOT2': "UnknownCardInPCIeSlot2",
            'UNKNOWNCARDINPCIESLOT3': "UnknownCardInPCIeSlot3",
            'UNKNOWNCARDINPCIESLOT4': "UnknownCardInPCIeSlot4",
            'ZONEINVALIDPCIEDEVICEREMOVAL': "ZoneInvalidPcieDeviceRemoval",
            'ZONEINVALIDSLOTCOMMUNICATIONFAILURE': "ZoneInvalidSlotCommunicationFailure",
            'ZONEINVALIDSWPOWERFAULT': "ZoneInvalidSwPowerFault",
            'ZONEINVALIDSWCOMMUNICATIONFAILURE': "ZoneInvalidSwCommunicationFailure",
            'PEERNVLINKEDGPUNOTMAPPED': "PeerNVLinkedGpuNotMapped",
            'ZONESREQUIRERECONFIG': "ZonesRequireReconfig",
            'RISER1GPUPIDMISMATCH': "Riser1GpuPidMismatch",
            'RISER2GPUPIDMISMATCH': "Riser2GpuPidMismatch",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'class_id': (str,),  # noqa: E501
            'object_type': (str,),  # noqa: E501
            'alarm_summary': (ComputeAlarmSummary,),  # noqa: E501
            'chassis_id': (str,),  # noqa: E501
            'firmware_version': (str,),  # noqa: E501
            'inventory_ready': (bool,),  # noqa: E501
            'lifecycle': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'oper_reason': ([str], none_type,),  # noqa: E501
            'oper_state': (str,),  # noqa: E501
            'package_version': (str,),  # noqa: E501
            'slot_id': (str,),  # noqa: E501
            'compute_blade': (ComputeBladeRelationship,),  # noqa: E501
            'equipment_chassis': (EquipmentChassisRelationship,),  # noqa: E501
            'graphics_cards': ([GraphicsCardRelationship], none_type,),  # noqa: E501
            'interconnects': ([EquipmentInterconnectRelationship], none_type,),  # noqa: E501
            'inventory_device_info': (InventoryDeviceInfoRelationship,),  # noqa: E501
            'locator_led': (EquipmentLocatorLedRelationship,),  # noqa: E501
            'registered_device': (AssetDeviceRegistrationRelationship,),  # noqa: E501
            'shared_graphics_cards': ([EquipmentSharedGraphicsCardRelationship], none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'class_id': 'ClassId',  # noqa: E501
        'object_type': 'ObjectType',  # noqa: E501
        'alarm_summary': 'AlarmSummary',  # noqa: E501
        'chassis_id': 'ChassisId',  # noqa: E501
        'firmware_version': 'FirmwareVersion',  # noqa: E501
        'inventory_ready': 'InventoryReady',  # noqa: E501
        'lifecycle': 'Lifecycle',  # noqa: E501
        'name': 'Name',  # noqa: E501
        'oper_reason': 'OperReason',  # noqa: E501
        'oper_state': 'OperState',  # noqa: E501
        'package_version': 'PackageVersion',  # noqa: E501
        'slot_id': 'SlotId',  # noqa: E501
        'compute_blade': 'ComputeBlade',  # noqa: E501
        'equipment_chassis': 'EquipmentChassis',  # noqa: E501
        'graphics_cards': 'GraphicsCards',  # noqa: E501
        'interconnects': 'Interconnects',  # noqa: E501
        'inventory_device_info': 'InventoryDeviceInfo',  # noqa: E501
        'locator_led': 'LocatorLed',  # noqa: E501
        'registered_device': 'RegisteredDevice',  # noqa: E501
        'shared_graphics_cards': 'SharedGraphicsCards',  # noqa: E501
    }

    read_only_vars = {
        'chassis_id',  # noqa: E501
        'firmware_version',  # noqa: E501
        'inventory_ready',  # noqa: E501
        'lifecycle',  # noqa: E501
        'name',  # noqa: E501
        'oper_state',  # noqa: E501
        'package_version',  # noqa: E501
        'slot_id',  # noqa: E501
        'graphics_cards',  # noqa: E501
        'interconnects',  # noqa: E501
        'shared_graphics_cards',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """PciNodeAllOf - a model defined in OpenAPI

        Args:

        Keyword Args:
            class_id (str): The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.. defaults to "pci.Node", must be one of ["pci.Node", ]  # noqa: E501
            object_type (str): The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.. defaults to "pci.Node", must be one of ["pci.Node", ]  # noqa: E501
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            alarm_summary (ComputeAlarmSummary): [optional]  # noqa: E501
            chassis_id (str): The id of the chassis that the PCIe node is currently located in.. [optional]  # noqa: E501
            firmware_version (str): The version of the PCIe node CIMC firmware.. [optional]  # noqa: E501
            inventory_ready (bool): The inventory ready field indicates whether the PCIe node management controller has completed inventory of the installed PCIe devices.. [optional]  # noqa: E501
            lifecycle (str): The lifecycle state of the PCIe node. This will map to the discovery lifecycle as represented in the Identity object. * `None` - Default state of an equipment. This should be an initial state when no state is defined for an equipment. * `Active` - Default Lifecycle State for a physical entity. * `Decommissioned` - Decommission Lifecycle state. * `DiscoveryInProgress` - DiscoveryInProgress Lifecycle state. * `DiscoveryFailed` - DiscoveryFailed Lifecycle state. * `FirmwareUpgradeInProgress` - Firmware upgrade is in progress on given physical entity. * `SecureEraseInProgress` - Secure Erase is in progress on given physical entity. * `ScrubInProgress` - Scrub is in progress on given physical entity. * `BladeMigrationInProgress` - Server slot migration is in progress on given physical entity. * `SlotMismatch` - The blade server is detected in a different chassis/slot than it was previously. * `Removed` - The blade server has been removed from its discovered slot, and not detected anywhere else. Blade inventory can be cleaned up by performing a software remove operation on the physically removed blade. * `Moved` - The blade server has been moved from its discovered location to a new location. Blade inventory can be updated by performing a rediscover operation on the moved blade. * `Replaced` - The blade server has been removed from its discovered location and another blade has been inserted in that location. Blade inventory can be cleaned up and updated by doing a software remove operation on the physically removed blade. * `MovedAndReplaced` - The blade server has been moved from its discovered location to a new location and another blade has been inserted into the old discovered location. Blade inventory can be updated by performing a rediscover operation on the moved blade.. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            name (str): The name of the PCIe node, the value of this property is the name of the UCS Domain along with the chassis and node slot ids.. [optional]  # noqa: E501
            oper_reason ([str], none_type): [optional]  # noqa: E501
            oper_state (str): Operational state of the PCIe node.. [optional]  # noqa: E501
            package_version (str): Bundle version which the CIMC firmware belongs to.. [optional]  # noqa: E501
            slot_id (str): The slot number in the chassis that the PCIe node is currently located in.. [optional]  # noqa: E501
            compute_blade (ComputeBladeRelationship): [optional]  # noqa: E501
            equipment_chassis (EquipmentChassisRelationship): [optional]  # noqa: E501
            graphics_cards ([GraphicsCardRelationship], none_type): An array of relationships to graphicsCard resources.. [optional]  # noqa: E501
            interconnects ([EquipmentInterconnectRelationship], none_type): An array of relationships to equipmentInterconnect resources.. [optional]  # noqa: E501
            inventory_device_info (InventoryDeviceInfoRelationship): [optional]  # noqa: E501
            locator_led (EquipmentLocatorLedRelationship): [optional]  # noqa: E501
            registered_device (AssetDeviceRegistrationRelationship): [optional]  # noqa: E501
            shared_graphics_cards ([EquipmentSharedGraphicsCardRelationship], none_type): An array of relationships to equipmentSharedGraphicsCard resources.. [optional]  # noqa: E501
        """

        class_id = "pci.Node" if len(kwargs.get('class_id','').strip()) == 0 else kwargs.get('class_id', "pci.Node")
        object_type = "pci.Node" if len(kwargs.get('object_type','').strip()) == 0 else kwargs.get('object_type', "pci.Node")
        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.class_id = class_id
        self.object_type = object_type
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """PciNodeAllOf - a model defined in OpenAPI

        Args:

        Keyword Args:
            class_id (str): The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.. defaults to "pci.Node", must be one of ["pci.Node", ]  # noqa: E501
            object_type (str): The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.. defaults to "pci.Node", must be one of ["pci.Node", ]  # noqa: E501
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            alarm_summary (ComputeAlarmSummary): [optional]  # noqa: E501
            chassis_id (str): The id of the chassis that the PCIe node is currently located in.. [optional]  # noqa: E501
            firmware_version (str): The version of the PCIe node CIMC firmware.. [optional]  # noqa: E501
            inventory_ready (bool): The inventory ready field indicates whether the PCIe node management controller has completed inventory of the installed PCIe devices.. [optional]  # noqa: E501
            lifecycle (str): The lifecycle state of the PCIe node. This will map to the discovery lifecycle as represented in the Identity object. * `None` - Default state of an equipment. This should be an initial state when no state is defined for an equipment. * `Active` - Default Lifecycle State for a physical entity. * `Decommissioned` - Decommission Lifecycle state. * `DiscoveryInProgress` - DiscoveryInProgress Lifecycle state. * `DiscoveryFailed` - DiscoveryFailed Lifecycle state. * `FirmwareUpgradeInProgress` - Firmware upgrade is in progress on given physical entity. * `SecureEraseInProgress` - Secure Erase is in progress on given physical entity. * `ScrubInProgress` - Scrub is in progress on given physical entity. * `BladeMigrationInProgress` - Server slot migration is in progress on given physical entity. * `SlotMismatch` - The blade server is detected in a different chassis/slot than it was previously. * `Removed` - The blade server has been removed from its discovered slot, and not detected anywhere else. Blade inventory can be cleaned up by performing a software remove operation on the physically removed blade. * `Moved` - The blade server has been moved from its discovered location to a new location. Blade inventory can be updated by performing a rediscover operation on the moved blade. * `Replaced` - The blade server has been removed from its discovered location and another blade has been inserted in that location. Blade inventory can be cleaned up and updated by doing a software remove operation on the physically removed blade. * `MovedAndReplaced` - The blade server has been moved from its discovered location to a new location and another blade has been inserted into the old discovered location. Blade inventory can be updated by performing a rediscover operation on the moved blade.. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            name (str): The name of the PCIe node, the value of this property is the name of the UCS Domain along with the chassis and node slot ids.. [optional]  # noqa: E501
            oper_reason ([str], none_type): [optional]  # noqa: E501
            oper_state (str): Operational state of the PCIe node.. [optional]  # noqa: E501
            package_version (str): Bundle version which the CIMC firmware belongs to.. [optional]  # noqa: E501
            slot_id (str): The slot number in the chassis that the PCIe node is currently located in.. [optional]  # noqa: E501
            compute_blade (ComputeBladeRelationship): [optional]  # noqa: E501
            equipment_chassis (EquipmentChassisRelationship): [optional]  # noqa: E501
            graphics_cards ([GraphicsCardRelationship], none_type): An array of relationships to graphicsCard resources.. [optional]  # noqa: E501
            interconnects ([EquipmentInterconnectRelationship], none_type): An array of relationships to equipmentInterconnect resources.. [optional]  # noqa: E501
            inventory_device_info (InventoryDeviceInfoRelationship): [optional]  # noqa: E501
            locator_led (EquipmentLocatorLedRelationship): [optional]  # noqa: E501
            registered_device (AssetDeviceRegistrationRelationship): [optional]  # noqa: E501
            shared_graphics_cards ([EquipmentSharedGraphicsCardRelationship], none_type): An array of relationships to equipmentSharedGraphicsCard resources.. [optional]  # noqa: E501
        """

        class_id = "pci.Node" if len(kwargs.get('class_id','').strip()) == 0 else kwargs.get('class_id', "pci.Node")
        object_type = "pci.Node" if len(kwargs.get('object_type','').strip()) == 0 else kwargs.get('object_type', "pci.Node")
        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.class_id = class_id
        self.object_type = object_type
        for var_name, var_value in kwargs.items():
            if var_name in self.read_only_vars:
                set_model_init_error(f"Warning : {var_name} is omitted from request payload as it is a read-only property")
                continue
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
